class Solution {
        private static final long INF = 4_000_000_000_000_000_000L; // 4e18

            public int findMaxPathScore(int[][] edges, boolean[] online, long k) {
                    int n = online.length;
                            List<List<int[]>> graph = new ArrayList<>(n);
                                    for (int i = 0; i < n; i++) {
                                                graph.add(new ArrayList<>());
                                                        }

                                                                int low = Integer.MAX_VALUE;
                                                                        int high = 0;

                                                                                for (int[] edge : edges) {
                                                                                            int u = edge[0];
                                                                                                        int v = edge[1];
                                                                                                                    int w = edge[2];
                                                                                                                                // Only consider edges where both endpoints are online
                                                                                                                                            if (online[u] && online[v]) {
                                                                                                                                                            graph.get(u).add(new int[]{v, w});
                                                                                                                                                                            low = Math.min(low, w);
                                                                                                                                                                                            high = Math.max(high, w);
                                                                                                                                                                                                        }
                                                                                                                                                                                                                }

                                                                                                                                                                                                                        int answer = -1;
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        // Binary search for the maximum possible "minimum edge cost"
                                                                                                                                                                                                                                                while (low <= high) {
                                                                                                                                                                                                                                                            int mid = low + (high - low) / 2;
                                                                                                                                                                                                                                                                        if (isPossible(0, mid, k, graph, n)) {
                                                                                                                                                                                                                                                                                        answer = mid;
                                                                                                                                                                                                                                                                                                        low = mid + 1;
                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                    high = mid - 1;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                return answer;
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                        private boolean isPossible(int start, int limit, long k, List<List<int[]>> graph, int n) {
                                                                                                                                                                                                                                                                                                                                                                                long[] dp = new long[n];
                                                                                                                                                                                                                                                                                                                                                                                        Arrays.fill(dp, -1);
                                                                                                                                                                                                                                                                                                                                                                                                return dfs(start, limit, graph, dp, n - 1) <= k;
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                        private long dfs(int node, int limit, List<List<int[]>> graph, long[] dp, int target) {
                                                                                                                                                                                                                                                                                                                                                                                                                if (node == target) return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                        if (dp[node] != -1) return dp[node];

                                                                                                                                                                                                                                                                                                                                                                                                                                long minCost = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int[] edge : graph.get(node)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    int neighbor = edge[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                int weight = edge[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Only traverse edges that meet the current threshold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (weight >= limit) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    long res = dfs(neighbor, limit, graph, dp, target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (res != INF) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        minCost = Math.min(minCost, (long) weight + res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return dp[node] = minCost;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
