import java.util.*;

class Solution {
    public long countMajoritySubarrays(int[] nums, int target) {
            int n = nums.length;
                    int[] arr = new int[n];
                            for (int i = 0; i < n; i++) {
                                        arr[i] = (nums[i] == target) ? 1 : -1;
                                                }

                                                        // Calculate prefix sums
                                                                int[] pref = new int[n + 1];
                                                                        for (int i = 0; i < n; i++) {
                                                                                    pref[i + 1] = pref[i] + arr[i];
                                                                                            }

                                                                                                    // Coordinate Compression for Fenwick Tree
                                                                                                            int[] sortedPref = pref.clone();
                                                                                                                    Arrays.sort(sortedPref);
                                                                                                                            
                                                                                                                                    // Remove duplicates to get unique ranks
                                                                                                                                            int m = 0;
                                                                                                                                                    for (int i = 0; i < sortedPref.length; i++) {
                                                                                                                                                                if (i == 0 || sortedPref[i] != sortedPref[i - 1]) {
                                                                                                                                                                                sortedPref[m++] = sortedPref[i];
                                                                                                                                                                                            }
                                                                                                                                                                                                    }

                                                                                                                                                                                                            FenwickTree ft = new FenwickTree(m);
                                                                                                                                                                                                                    long count = 0;
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    for (int p : pref) {
                                                                                                                                                                                                                                                int rank = Arrays.binarySearch(sortedPref, 0, m, p);
                                                                                                                                                                                                                                                            // Count how many previous prefix sums are strictly less than current p
                                                                                                                                                                                                                                                                        count += ft.query(rank); 
                                                                                                                                                                                                                                                                                    // Update Fenwick tree with current prefix sum
                                                                                                                                                                                                                                                                                                ft.update(rank + 1, 1);
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        return count;
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                private static class FenwickTree {
                                                                                                                                                                                                                                                                                                                                        int[] tree;
                                                                                                                                                                                                                                                                                                                                                FenwickTree(int n) { tree = new int[n + 1]; }
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                void update(int i, int delta) {
                                                                                                                                                                                                                                                                                                                                                                            for (; i < tree.length; i += i & -i) tree[i] += delta;
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                    int query(int i) {
                                                                                                                                                                                                                                                                                                                                                                                                                int sum = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                            for (; i > 0; i -= i & -i) sum += tree[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                        return sum;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }