class Solution {
        public int maximumLength(int[] nums) {
                // Map to store frequency of each number
                        java.util.Map<Long, Integer> count = new java.util.HashMap<>();
                                for (int num : nums) {
                                            count.put((long) num, count.getOrDefault((long) num, 0) + 1);
                                                    }

                                                            int maxLen = 0;

                                                                    // 1 is a special case. If we have n 1s, we can take an odd number of them.
                                                                            if (count.containsKey(1L)) {
                                                                                        int ones = count.get(1L);
                                                                                                    maxLen = (ones % 2 == 0) ? ones - 1 : ones;
                                                                                                            }

                                                                                                                    // For x > 1, the sequence x, x^2, x^4... increases very rapidly.
                                                                                                                            // We only need to check short chains for each number in the map.
                                                                                                                                    for (long x : count.keySet()) {
                                                                                                                                                if (x == 1) continue;

                                                                                                                                                            long curr = x;
                                                                                                                                                                        int currentLen = 0;
                                                                                                                                                                                    
                                                                                                                                                                                                // Try to build the chain: x, x^2, x^4, ...
                                                                                                                                                                                                            while (count.containsKey(curr) && count.get(curr) >= 2) {
                                                                                                                                                                                                                            currentLen += 2;
                                                                                                                                                                                                                                            curr *= curr;
                                                                                                                                                                                                                                                            // Safety break for extremely large numbers
                                                                                                                                                                                                                                                                            if (curr > 1_000_000_000L) break;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                // If the final number exists, include it in the sequence
                                                                                                                                                                                                                                                                                                                            if (count.containsKey(curr)) {
                                                                                                                                                                                                                                                                                                                                            currentLen += 1;
                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                        // Otherwise, backtrack to maintain the symmetric pattern
                                                                                                                                                                                                                                                                                                                                                                                        currentLen -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                            maxLen = Math.max(maxLen, currentLen);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                            return maxLen;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                            