import java.util.*;

class Solution {
    // DSU helper class to manage connectivity
        private static class DSU {
                int[] parent;
                        int count;

                                public DSU(int n) {
                                            parent = new int[n];
                                                        for (int i = 0; i < n; i++) parent[i] = i;
                                                                    count = n;
                                                                            }

                                                                                    public int find(int i) {
                                                                                                if (parent[i] == i) return i;
                                                                                                            return parent[i] = find(parent[i]);
                                                                                                                    }

                                                                                                                            public boolean union(int i, int j) {
                                                                                                                                        int rootI = find(i);
                                                                                                                                                    int rootJ = find(j);
                                                                                                                                                                if (rootI != rootJ) {
                                                                                                                                                                                parent[rootI] = rootJ;
                                                                                                                                                                                                count--;
                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        public int maxStability(int n, int[][] edges, int k) {
                                                                                                                                                                                                                                                                int low = 0, high = 200000;
                                                                                                                                                                                                                                                                        int ans = -1;

                                                                                                                                                                                                                                                                                while (low <= high) {
                                                                                                                                                                                                                                                                                            int mid = low + (high - low) / 2;
                                                                                                                                                                                                                                                                                                        if (check(n, edges, k, mid)) {
                                                                                                                                                                                                                                                                                                                        ans = mid;
                                                                                                                                                                                                                                                                                                                                        low = mid + 1;
                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                    high = mid - 1;
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                return ans;
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                        private boolean check(int n, int[][] edges, int k, int limit) {
                                                                                                                                                                                                                                                                                                                                                                                                                DSU dsu = new DSU(n);
                                                                                                                                                                                                                                                                                                                                                                                                                        int upgradesUsed = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                // 1. Mandatory edges MUST be added first
                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int[] edge : edges) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (edge[3] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // If a mandatory edge is weaker than our target stability, this limit is impossible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (edge[2] < limit) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!dsu.union(edge[0], edge[1])) return false; // Cycle detected in mandatory edges
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 2. Add optional edges that already meet the requirement
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int[] edge : edges) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (edge[3] == 0 && edge[2] >= limit) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dsu.union(edge[0], edge[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Greedily use remaining upgrades on edges that can reach the limit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int[] edge : edges) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (edge[3] == 0 && edge[2] < limit && edge[2] * 2 >= limit) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (upgradesUsed < k && dsu.union(edge[0], edge[1])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        upgradesUsed++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Check if all nodes are connected (single component)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return dsu.count == 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }