import java.util.*;

class Solution {
    private static class Node {
            int l, r, mn, mx, lazy;
                }

                    private Node[] tr;

                        public int longestBalanced(int[] nums) {
                                int n = nums.length;
                                        tr = new Node[4 * (n + 1)];
                                                for (int i = 0; i < tr.length; i++) tr[i] = new Node();
                                                        
                                                                build(1, 0, n);
                                                                        
                                                                                Map<Integer, Integer> last = new HashMap<>();
                                                                                        int now = 0, ans = 0;
                                                                                                
                                                                                                        for (int i = 1; i <= n; i++) {
                                                                                                                    int x = nums[i - 1];
                                                                                                                                int det = (x % 2 != 0) ? 1 : -1;
                                                                                                                                            
                                                                                                                                                        if (last.containsKey(x)) {
                                                                                                                                                                        modify(1, last.get(x), n, -det);
                                                                                                                                                                                        now -= det;
                                                                                                                                                                                                    }
                                                                                                                                                                                                                
                                                                                                                                                                                                                            last.put(x, i);
                                                                                                                                                                                                                                        modify(1, i, n, det);
                                                                                                                                                                                                                                                    now += det;
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                            int pos = query(1, now);
                                                                                                                                                                                                                                                                                        ans = Math.max(ans, i - pos);
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                        return ans;
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                private void build(int u, int l, int r) {
                                                                                                                                                                                                                                                                                                                        tr[u].l = l; tr[u].r = r;
                                                                                                                                                                                                                                                                                                                                if (l == r) return;
                                                                                                                                                                                                                                                                                                                                        int mid = (l + r) >> 1;
                                                                                                                                                                                                                                                                                                                                                build(u << 1, l, mid);
                                                                                                                                                                                                                                                                                                                                                        build(u << 1 | 1, mid + 1, r);
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                private void apply(int u, int v) {
                                                                                                                                                                                                                                                                                                                                                                        tr[u].mn += v; tr[u].mx += v; tr[u].lazy += v;
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                private void pushdown(int u) {
                                                                                                                                                                                                                                                                                                                                                                                        if (tr[u].lazy != 0) {
                                                                                                                                                                                                                                                                                                                                                                                                    apply(u << 1, tr[u].lazy);
                                                                                                                                                                                                                                                                                                                                                                                                                apply(u << 1 | 1, tr[u].lazy);
                                                                                                                                                                                                                                                                                                                                                                                                                            tr[u].lazy = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            private void modify(int u, int l, int r, int v) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (tr[u].l >= l && tr[u].r <= r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                apply(u, v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pushdown(u);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int mid = (tr[u].l + tr[u].r) >> 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (l <= mid) modify(u << 1, l, r, v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (r > mid) modify(u << 1 | 1, l, r, v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tr[u].mn = Math.min(tr[u << 1].mn, tr[u << 1 | 1].mn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tr[u].mx = Math.max(tr[u << 1].mx, tr[u << 1 | 1].mx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private int query(int u, int target) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (tr[u].l == tr[u].r) return tr[u].l;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pushdown(u);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Look in the left child if the target is within its range [mn, mx]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (tr[u << 1].mn <= target && target <= tr[u << 1].mx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return query(u << 1, target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return query(u << 1 | 1, target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }