import java.util.*;

class Solution {
    private record Sequence(int startX, int startY, int endX, int endY, int length) {}

        public int maxDistance(int side, int[][] points, int k) {
                List<int[]> ordered = getOrderedPoints(side, points);
                        int l = 0;
                                int r = side;
                                        
                                                while (l < r) {
                                                            int m = (l + r + 1) / 2;
                                                                        if (isValid(ordered, k, m)) {
                                                                                        l = m;
                                                                                                    } else {
                                                                                                                    r = m - 1;
                                                                                                                                }
                                                                                                                                        }
                                                                                                                                                return l;
                                                                                                                                                    }

                                                                                                                                                        private boolean isValid(List<int[]> ordered, int k, int d) {
                                                                                                                                                                int n = ordered.size();
                                                                                                                                                                        // Use a deque to maintain valid sequences of points
                                                                                                                                                                                Deque<Sequence> dq = new ArrayDeque<>();
                                                                                                                                                                                        dq.add(new Sequence(ordered.get(0)[0], ordered.get(0)[1], ordered.get(0)[0], ordered.get(0)[1], 1));
                                                                                                                                                                                                
                                                                                                                                                                                                        int maxLength = 1;
                                                                                                                                                                                                                for (int i = 1; i < n; i++) {
                                                                                                                                                                                                                            int x = ordered.get(i)[0];
                                                                                                                                                                                                                                        int y = ordered.get(i)[1];
                                                                                                                                                                                                                                                    int startX = x, startY = y, length = 1;

                                                                                                                                                                                                                                                                while (!dq.isEmpty() && (Math.abs(x - dq.peekFirst().endX()) + Math.abs(y - dq.peekFirst().endY()) >= d)) {
                                                                                                                                                                                                                                                                                Sequence head = dq.pollFirst();
                                                                                                                                                                                                                                                                                                if (Math.abs(x - head.startX()) + Math.abs(y - head.startY()) >= d && head.length() + 1 >= length) {
                                                                                                                                                                                                                                                                                                                    startX = head.startX();
                                                                                                                                                                                                                                                                                                                                        startY = head.startY();
                                                                                                                                                                                                                                                                                                                                                            length = head.length() + 1;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                    maxLength = Math.max(maxLength, length);
                                                                                                                                                                                                                                                                                                                                                                                                                dq.addLast(new Sequence(startX, startY, x, y, length));
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                return maxLength >= k;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        private List<int[]> getOrderedPoints(int side, int[][] points) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                List<int[]> left = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        List<int[]> top = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                List<int[]> right = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        List<int[]> bottom = new ArrayList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int[] p : points) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (p[0] == 0 && p[1] > 0) left.add(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if (p[1] == side && p[0] > 0) top.add(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (p[0] == side && p[1] < side) right.add(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else bottom.add(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                left.sort(Comparator.comparingInt(a -> a[1]));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        top.sort(Comparator.comparingInt(a -> a[0]));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                right.sort((a, b) -> Integer.compare(b[1], a[1]));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bottom.sort((a, b) -> Integer.compare(b[0], a[0]));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                List<int[]> res = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.addAll(left);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.addAll(top);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.addAll(right);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.addAll(bottom);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }