import java.util.*;

class Solution {
    public int minJumps(int[] arr) {
            int n = arr.length;
                    if (n <= 1) return 0;

                            // Map each value to a list of its indices
                                    Map<Integer, List<Integer>> graph = new HashMap<>();
                                            for (int i = 0; i < n; i++) {
                                                        graph.computeIfAbsent(arr[i], k -> new ArrayList<>()).add(i);
                                                                }

                                                                        Queue<Integer> queue = new LinkedList<>();
                                                                                boolean[] visited = new boolean[n];
                                                                                        
                                                                                                queue.offer(0);
                                                                                                        visited[0] = true;
                                                                                                                int steps = 0;

                                                                                                                        while (!queue.isEmpty()) {
                                                                                                                                    int size = queue.size();
                                                                                                                                                for (int i = 0; i < size; i++) {
                                                                                                                                                                int curr = queue.poll();

                                                                                                                                                                                // If we reached the last index
                                                                                                                                                                                                if (curr == n - 1) return steps;

                                                                                                                                                                                                                List<Integer> nextIndices = new ArrayList<>();
                                                                                                                                                                                                                                // 1. Jump to i + 1
                                                                                                                                                                                                                                                if (curr + 1 < n) nextIndices.add(curr + 1);
                                                                                                                                                                                                                                                                // 2. Jump to i - 1
                                                                                                                                                                                                                                                                                if (curr - 1 >= 0) nextIndices.add(curr - 1);
                                                                                                                                                                                                                                                                                                // 3. Jump to all other indices with same value
                                                                                                                                                                                                                                                                                                                if (graph.containsKey(arr[curr])) {
                                                                                                                                                                                                                                                                                                                                    nextIndices.addAll(graph.get(arr[curr]));
                                                                                                                                                                                                                                                                                                                                                        // CRITICAL: Clear the list to ensure O(n) time complexity
                                                                                                                                                                                                                                                                                                                                                                            graph.remove(arr[curr]);
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            for (int next : nextIndices) {
                                                                                                                                                                                                                                                                                                                                                                                                                                if (!visited[next]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        visited[next] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue.offer(next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            steps++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }